### ISSUE TITLE
Empty body response for XML.

### ISSUE THREAD

**Issue by asimen1** [chaijs/chai-http#169] opened 2017-08-16 14:23 UTC
[code gist](https://gist.github.com/asimen1/0456843afe28603299a86c5ffbecbb1d)

Running the above code does not parse the response.body XML correctly, returning an empty object.

**Comment by keithamus** [comment] 2017-08-16 15:20
Thanks for the isssue @asimen1 

It looks like the URL you're fetching doesn't reply with a `Content-Type` header, and so there's no way to determine what type it is. Have a read of [the s3 docs](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html), or maybe [this stackoverflow answer](https://stackoverflow.com/questions/29643455/how-do-i-set-content-type-when-uploading-to-s3-with-aws-cli) in order to get s3 to send a content-type header, otherwise you could look at using the `.type` method to manually set it. Here's the relevant SuperAgent source about that:

https://github.com/visionmedia/superagent/blob/4e21f1c509c3ee09ea4031c27855ed8e9ddc0d35/lib/client.js#L447-L472.

I'll close this issue, as it's not a bug within our code, but if you have any more problems don't hesitate to continue commenting here or in another issue.

**Closed by keithamus** 2017-08-16 15:20 UTC

**Comment by asimen1** [comment] 2017-08-16 16:16
Hi @keithamus, thanks for the quick response!

Your right, this URL did not have any content-type.
This is just a dummy URL I created for this issue, however I encountered the problem in our server response which does add the content-type header 'application/xml'.

I added now the header to the S3 URL response and still returnes an empty body.
You can test it again now...

Is there anything else I'm missing?
Thanks.

**Comment by keithamus** [comment] 2017-08-17 09:06
You can see the [suppported types here](https://github.com/visionmedia/superagent/blob/4e21f1c509c3ee09ea4031c27855ed8e9ddc0d35/lib/client.js#L169-L176). `application/xml` is not in that list, so you'll have to manually add `type('xml')` or change the content type to `text/xml`. Alternatively, if you believe superagent should read `application/xml` you could raise a pull request with them - and we'll be able to pull the changes downstream in the next release.
