### ISSUE TITLE
Chai always passes tests when using Promises

### ISSUE THREAD

**Issue by eluchsinger** [chaijs/chai-http#179] opened 2017-10-16 16:07 UTC
The following code should fail (obviously). But it doesn't fail, it passes without calling the then function or the catch function. It fails, if I add the done parameter. Am I doing something wrong?

```
it('Returns the correct amount of events', function() {
	chai.request(app)
		.get('/api/events/count')
		.then(function(res) {
			throw new Error('why no throw?');
			expect(res).to.have.status(200);
			expect(res).to.be.json;
		})
		.catch(function(err) {
			throw err;
		});
});
```

**Comment by keithamus** [comment] 2017-10-18 16:42
Hey @eluchsinger thanks for the issue.

When using Promises, you need to let mocha know your code is async. The easiest way to do this is to `return` the Promise to mocha:

```js
it('Returns the correct amount of events', function() {
	return chai.request(app)
		.get('/api/events/count')
		.then(function(res) {
			throw new Error('why no throw?');
			expect(res).to.have.status(200);
			expect(res).to.be.json;
		})
		.catch(function(err) {
			throw err;
		});
});
```
(Notice the `return` keyword)

Hopefully this solves your issue. As this is not a bug, I'm going to close this issue - but if you do think it is a bug please feel free to continue the discussion and we can re-open this.

**Closed by keithamus** 2017-10-18 16:42 UTC

**Comment by capttrousers** [comment] 2017-10-28 00:13
I am using the return with the promise but I am getting weird passing behavior as well:

```
    return chai.request(app).post('/users/login').send(body).then(function(res) {
      logger.info("login succeeds")
      expect(res).to.have.status(200);
    }).catch(function(err) {
      logger.info("login fails")
      expect(err.response).to.have.status(400);
      expect(err.response.text).to.equal("Invalid email or password")
    });
```

If I run that, everything runs like I expect, if the server returns a 200. If I change the 200 in the expect assertion to a different status code, it errors `AssertionError: Target cannot be null or undefined.` and logs both messages, from the then() and catch() blocks which is unexpected. I'd just expect the assertion to fail.

**Comment by keithamus** [comment] 2017-10-28 10:07
your `catch` will also catch errors from the `then` block, do avoid this you can combine them into one `then`:

```js
    return chai.request(app).post('/users/login').send(body).then(function(res) {
      logger.info("login succeeds")
      expect(res).to.have.status(200);
    }, function(err) { // notice this line has shifted from `.catch` to being the second `.then` param
      logger.info("login fails")
      expect(err.response).to.have.status(400);
      expect(err.response.text).to.equal("Invalid email or password")
    });
```

**Comment by blakemorgan** [comment] 2019-03-19 03:01
I'm having a similar error. I have catch blocks and the return statement, but I still get the uncaught promise warning. Is there something I'm missing?

```javascript
  it('GET /api/users/current: allowed with token', function () {
    const agent = chai.request.agent(server)
    agent
      .post('/api/users')
      .send({
        'user': {
          'email': 'test@email.com',
          'password': 'test'
        }
      })
      .then(function (res) {
        expect(res).to.have.cookie('dbmtg_jwt')
        agent.get('/api/user/current')
          .then(function (res) {
            expect(res).to.be.json
            expect(res.body).to.have.all.keys('_id', 'email', 'token')
          })
          .catch(function (err) {
            throw err
          })
      })
      .catch(function (err) {
        throw err
      })
  })
```
