### ISSUE TITLE
How to properly test for HTTP failure responses

### ISSUE THREAD

**Issue by rvnath** [chaijs/chai-http#84] opened 2016-03-26 10:11 UTC
I am trying to test a condition wherein the API returns 500 (internal server error).  I am doing the expect assertion in the catch block like this:

```javascript
  it ('Creation of user without email address, should fail', function(done) {
      chai.request(app).post('/users')
         .send(sampleUsers.userWithoutEmail)
         .then(function(res) {
            return done(new Error('should have failed with 400'));
      }).catch(function(e){
        console.log("error:", e.status);
        expect(e).to.have.status(400);  // shd fail with 'bad request'
        return done();
      });
    });
```

The problem with this is, it gets stuck at the expect line and doesn't come out until test framework times out.  I can see that the console.log line gets printed correctly without consuming time, but expect invocation doesn't finish. 

 What am I doing wrong here?
Is this the correct way to test errors?

**Comment by atom-morgan** [comment] 2016-10-10 19:45
I'm also seeing this behavior. I can chain with `then` just fine and test successful responses but the second I need to test a failure with `catch` my response behaves a bit differently.

In my API my response is `return res.status(404).json({ error: 'User could not be found' });`

If I use chai-http's `end`, I can test the failure successfully like this:

```
.end((err, res) => {
  res.should.have.status(404);
  res.body.should.have.property('error');
  res.body.error.should.eql('User could not be found');
  done();
});
```

But when I switch to chai-http's promises, I can't test directly on `err` within the chained `catch` - I have to add `response` to `err` as well. Am I doing something wrong here?

```
.catch((err) => {
  err.response.should.have.status(404);
  err.response.body.should.have.property('error');
  err.response.body.error.should.eql('User could not be found');
});
```

**Comment by keithamus** [comment] 2016-10-10 19:48
Thanks for the issue @rvnath. This looks a lot like a dupe of #75. If we could continue the discussion there that'd be great. I'll close this one.

**Closed by keithamus** 2016-10-10 19:48 UTC
