### ISSUE TITLE
Status codes different than 2xx shouldn't be trated as Promise rejections

### ISSUE THREAD

**Issue by castarco** [chaijs/chai-http#115] opened 2016-09-22 10:57 UTC
Since Chai-Http is a testing utility, it shouldn't make the assumption that not 2xx responses are errors, because maybe (and probably) we're expecting status codes in the 4xx range (or in other ranges).

At this time, I have place a catch before the "then" call because the "then" method isn't triggered, and the last "catch" is triggered, making fail the test.

Example:

```javascript
it('GET /agents/status with invalid appId returns 401 status and "Invalid app ID" message', function () {
        return serverPromise
            .then(function (server) {
                return chai.request(server).get('/agents/status?appId=');
            })
            .catch(function (err) {
                // not 2xx responses are treated as errors :( , it sucks.
                return err.hasOwnProperty('response') ? err.response : err;
            })
            .then(function (res) {
                res.should.have.status(401);
                res.body.should.have.property('error');
                res.body.error.should.have.property('message');
                res.body.error.message.should.equal('Invalid app ID');
            })
            .catch(registerError);
    });
```

without the first catch, which converts the error again to be a response, the last one is triggered... but this one is placed there to catch **real** errors, not the expected ones.

**Comment by keithamus** [comment] 2016-09-23 09:45
Hey @castarco thanks for the issue. This is a dupe of #75 so let's continue the discussion there!

**Closed by keithamus** 2016-09-23 09:45 UTC
