### ISSUE TITLE
Question - Getting Inconsistent Behavior with Stub

### ISSUE THREAD

**Issue by Swhite215** [chaijs/chai-http#271] opened 2020-06-02 20:40 UTC
I am working on stubbing a function that is called in an endpoint that I am testing using chai-http. I am curious about some behavior that I am seeing.

I have provided the working and failing chunks of code below. To get to the point, the working set of code passes when done is provided in the it statement callback function and then done() is called after my assertion. When I don't provide done and don't call it, the function I am trying to stub is never stubbed. Is this intended behavior? Could someone describe why this is happening?

Working Code - Function stubbed correctly - done used:
```
describe("Part Endpoints Integration Tests", function() {
    describe("POST /part - Endpoint to create a new part", function() {
        let mockObj;

        beforeEach(function() {
            mockObj = sinon.stub(partService, "createPart");
        });

        afterEach(function() {
            mockObj.restore()
        });

        it("should be an endpoint that creates a new part", function(done) {

            mockObj.resolves(true);

            chai
            .request(app)
            .post(`/part`)
            .send({
                custodian: "Assembly",
                custodianName: "Assembly",
                partNumber: "AB_1",
                serialNumber: "ASDKJAS121",
                geoLocation: "Dearborn, MI"
            })
            .end((err, res) => {
                res.should.have.status(200);
                done();
            });
        });
    });
});
```

Failing Code - Function NOT stubbed correctly - done unused:
```
describe("Part Endpoints Integration Tests", function() {
    describe("POST /part - Endpoint to create a new part", function() {
        let mockObj;

        beforeEach(function() {
            mockObj = sinon.stub(partService, "createPart");
        });

        afterEach(function() {
            mockObj.restore()
        });

        it("should be an endpoint that creates a new part", function() {

            mockObj.resolves(true);

            chai
            .request(app)
            .post(`/part`)
            .send({
                custodian: "Assembly",
                custodianName: "Assembly",
                partNumber: "AB_1",
                serialNumber: "ASDKJAS121",
                geoLocation: "Dearborn, MI"
            })
            .end((err, res) => {
                res.should.have.status(200);
            });
        });
    });
});
```

**Comment by austince** [comment] 2020-06-02 20:53
HI @Swhite215, yes I think this is expected behavior, but definitely a little weird. I believe what you're seeing is a race condition where Mocha finishes running your test before the HTTP request is executed since Mocha tests are synchronous by default and HTTP requests are asynchronous. When you pass the `done` argument to the test, Mocha configures it as an async test.

If possible, I've found it easier to use either `async`/`await` with Mocha and chai-http or to return the `Promise` from `chai.request(app)...` directly, which is another way to tell Mocha that the test is async. 

Ex: 

Returning a `Promise`:
```javascript
      it("should be an endpoint that creates a new part", function() {
            mockObj.resolves(true);

            return chai
            .request(app)
            .post(`/part`)
             // ...
            .then((res) => {
                res.should.have.status(200);
            });
        });
```



`async`/`await`:
```javascript
      it("should be an endpoint that creates a new part", async function() {
            mockObj.resolves(true);

            const res = await chai
            .request(app)
            .post(`/part`)
             // ...
             // no `end` or `then`!
             res.should.have.status(200);
        });
```


Going to close this as I don't think it's an issue with `chai-http`, but let me know if that makes sense!

**Closed by austince** 2020-06-02 20:53 UTC

**Comment by Swhite215** [comment] 2020-06-03 20:59
Thank you that makes sense. I appreciate the prompt response.
