### ISSUE TITLE
It's not working with response - Promises.

### ISSUE THREAD

**Issue by Bhavin305** [chaijs/chai-http#124] opened 2016-11-09 13:01 UTC
I have tried with q and es6-promise...in get method getting UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: res.send is not a function and i am able to console the response in express server just before res.json line.

**Comment by meeber** [comment] 2016-11-09 14:27
@Bhavin305 Can you reproduce the issue in a small repo for us to see? We don't currently have enough information to help troubleshoot.

**Comment by meeber** [comment] 2016-12-15 23:32
@Bhavin305 Closing this due to lack of information. Please feel welcome to reopen it if you have a standalone example to share that demonstrates the problem.

**Closed by meeber** 2016-12-15 23:32 UTC
